FROM python:3.9-slim-buster

WORKDIR /code

# Instale as dependências do backend
COPY dev-requirements.txt  .
RUN pip install --upgrade pip
RUN pip install -r dev-requirements.txt

# Copie o código do backend
COPY backend/src /code/backend

# Copie o código do frontend
COPY frontend/src /code/frontend

# Defina variáveis de ambiente, se necessário
ENV ENV dev
# Expor as portas, se necessário
EXPOSE 8000 8080

# Comando para iniciar o aplicativo
CMD ["sh", "-c", "gunicorn backend.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 & gunicorn frontend.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"]
