version: "3.9"

networks:
  mynetwork:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - mynetwork
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    restart: always

  app:
    container_name: customer-care-ai 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - OPENAI_API_KEY= # Your OPENAI KEY
      - DB_HOST_DEV=mongo
      - DB_PASSWORD_DEV=example
      - DB_DATABASE_DEV=customer-care-db
      - DB_PORT_DEV=27017
      - DB_USER=mongo
      - ENV=dev
    ports: 
      - 8000:8000 
      - 8080:8080
    restart: always
    networks:
      - mynetwork


